travis:
  secure:
    BINSTAR_TOKEN: gQykgGQW0+a6+yxnV76dL0lkkODC4dRyRDxwrdpND9zfF7YkRmpLj2YVUO3NZPaMx5MDHevLUyISZ5aVnbbXn3W1XnO8IEhoGSH+uKUVKtgE9nZCCauw3ncRl+4Qor2aa118m71BFN+R/fnU+MguB0ozK9oFf8+x4/F+QhbDWzGrYOFjDx88a5QVwWd/3Cbjm0Wfb84N4jvB8reuCdzYF/06rCfGD/a/kpEDNbgFSZk8ACKd9NzTWVk2TtiWKLrWF8QbvfmIGINn3aLc883CDNRW5+uNZi+m53jP8HNBd9KeCT0NzUn4DuWdP/rUi5oDUgTNoGKF+T2soMrU9IfUBJ911l8V4wKQINTcOHpIUA+P04Zh7eusQmSCsIsE8izQhnpql5LE7tsdHHT5yNkGJRhWPJRJ4svESSQ+htpFA3nfaTdXHb1rJyfr9YVmj/2iXx4oDRrWV54NhTuEYYkDFwSed6g0HiO2ynY2cAbuTsUo7YeZQuVD1EMrIETt6hJsREmzYinWPBKr3MqIx9aRnN98FtCbwbB9278B+oey4joDm7utp6+Ka0LHsB9njDLMnJ4nl93VfuXrVFA2R7A5FHXCuxrL2SugRTrqvBZPh6jVHRmGoNLK78KrfglzYGlqZgZGcDiP4exnwUzC7ZlbubeHyP/RuQFHKF4RBzrgR4U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
