travis:
  secure:
    BINSTAR_TOKEN: S+CMzJf0xs4CVJeriddqi0QCvcf/3GM+TgG0+NoReYg+SZaX0UIm9WbPKTL5Ho0ckzLpaRllL6guMeHoO1hpjIPKpWfOH+4tjgoWlRHtZG15EoCwIN6hN3yJjJsaN/wSw46J1tREy5+/GXnMW+YRKlQhrg/gEhe+bFngww9Gmu7xe9a8mMjb3ktq7o7ELY/Zu+WmBQoPVy2K+tfBrJgm+eTYT1ModHruMNX9p07yREtbw9QRJs071kjM29I/7eMeURms9zJoTEv2MdqdM6gK9Yei/HDon2G1sWdQdCPjMqE36G7h9XOtQmn2JN4EXa4DAH8EF6H+iPL0+s9srlJDb/zyhH8aRzgLk/RmylB/KM92DPN4WwSLFV4UddzWqS/iKt1vIN+xNjPWF9zbx1M9FWvq2trz4pqIwthUihO1ZiqCiZaR0g/Ba10KmiMnKoYnqml9CCxfuOQYwjnjsGZbAsSTPWfUJYNhcmburaAbkikjzQ0HwH+p2kw/tNxjjqxILp8KPw82iTnljUZwWkg4wgqT9k4sL1rLGPQlURdJxHhca4D2ZbeH8kLgpGKEF7/9j/RWUnjAypszSvBinhszvygTt+bq3ABcdV7eOlL1WbsLSSt6NpHwk8NP9iFUwbghXu4H3YIQdKaQFooWZ9xQ645OZoIV7RLnB/Z2wQlqBD0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
