travis:
  secure:
    BINSTAR_TOKEN: eVldxiLocGyvptPtaDkaxCB5bp6h4Ei1QIH975Z3mgR/QcudPPC/JIAt/BMZB3sTMpzsqMzh9wchtNQGSQ40D8E39vwszQWxdeUxoV3a50dk+26K5eHQxHujmbG+hWbs4HQVVcJ/IhRQWPzj+nVJFDV6tJ+9zUdglSji4bPxgQG8chhnCW/qs46hsFroec7+jZIZ33JfeXzYxKLFeIq9pEq02TkCI6REbNrIhr40BDqPPu3RMMf9fmiXQNzeZntjVU4euP5sv7BrlqbGp9uiK5/BxfcqQQT9im2WAvE/+lmRCJ/aTDzU4q/oNLU5aNZt0TCagwQH0KL/z7xfdDfZ9C/aDmhPy1cZ8uJpPam5jwAA3B6On+ao1/Fc/A+k5WJsDiM0Pq9IbHvUwxnjOE42UTivKkqopvtW8cK++TUWWo/DVUyEt7uZesiX27Fi0mGSD7OQULH/aaHDpWuNJOTfTbXyfnP9xKHFh3zClr7dxWCHVcJd6cdqFVgF0Hiy12gG3rMqy7JRbEiZrOrsFjLlsWJbHdercuNbgg4EhRG0RCqKIOF4jUxrnxTBuam4/+/I5kjQa6ZAADq75Jc/dI2Jtjk6cSJB03Q5ZRJ1k6CCBtxt5UwgMSDCBOhmRKIDp6s2XbYW51FemBBFbOIP1774h9DXOk+RpNErYLHRnz1Xg6Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
